# Generated by Django 3.2.9 on 2021-11-25 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0003_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
