# Generated by Django 3.2.9 on 2021-11-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0007_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('items', models.ManyToManyField(to='resturant.Item')),
                ('order', models.ManyToManyField(to='resturant.Order')),
            ],
        ),
    ]
