# Generated by Django 3.2.9 on 2021-12-31 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0009_auto_20211231_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='resturant',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
