# Generated by Django 3.2.9 on 2021-12-31 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resturant', '0011_auto_20211231_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='resturant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resturant.resturant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resturant.item'),
        ),
    ]
