# Generated by Django 3.2.9 on 2021-11-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0003_auto_20211125_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='detail',
            field=models.JSONField(default=dict),
        ),
    ]
