# Generated by Django 3.2.9 on 2021-11-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0005_auto_20211126_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
