# Generated by Django 3.2.9 on 2021-11-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0006_rename_cart_id_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='complete this!'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='01xxxxxxxxx', max_length=11),
            preserve_default=False,
        ),
    ]
