# Generated by Django 3.2.9 on 2021-11-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0010_remove_cart_resturant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
