# Generated by Django 3.2.9 on 2021-11-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0014_alter_cart_resturant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='resturant',
        ),
    ]
