# Generated by Django 3.2.9 on 2021-12-31 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0009_auto_20211231_1636'),
        ('user1', '0015_remove_cart_resturant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='resturant',
        ),
        migrations.AddField(
            model_name='cart',
            name='resturant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='resturant.resturant'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user1.cart'),
        ),
    ]
