# Generated by Django 4.0.3 on 2022-03-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0018_auto_20211231_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(default='need edit'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
